### ISSUE TITLE
Cannot read property 'matches' of null

### ISSUE THREAD

**Issue by briangonzalez** [desandro/matches-selector#6]
We've been trying to track down an exception in production which reads:

```
Cannot read property 'matches' of null
```

We've grepped around the codebase and have found that this library potentially could be more defensive if `Element.prototype` is not defined. 

https://github.com/desandro/matches-selector/blob/master/matches-selector.js#L30

We're not 100% sure this is the issue, but seems highly plausible. Thoughts?

### Screenshot:

<img width="1250" alt="screen shot 2016-04-09 at 10 15 32 am" src="https://cloud.githubusercontent.com/assets/659829/14405126/4c7b497c-fe3c-11e5-8a22-f442c06f37b6.png">

**Comment by desandro** [comment]
I'd say yes, this library is likely the cause of the issue. What sort of browser/environment is this code running in? matchesSelector v2 supports IE10+ and modern browsers that have `Element.prototype`. If you're running this server side, where browser features are not supported, matchesSelector shouldn't be run.

**Comment by briangonzalez** [comment]
What would a more defensive version of this code look like?

We're only using this in the browser at the moment, btw.

**Comment by desandro** [comment]
You could try using [matchesSelector v1](https://github.com/desandro/matches-selector/releases/tag/v1.0.3)

**Comment by briangonzalez** [comment]
What do you recommend I do if I am not using matchesSelector directly, but through flickity? Fork and build?

**Comment by desandro** [comment]
In Flickity, `matchesSelector` is only used in one place, [within `Flickity.prototype.staticClick`](https://github.com/metafizzy/flickity/blob/v1.2.1/js/drag.js#L320). If `staticClick` is triggered on a node that is not an element, then it could cause this bug.

**Comment by briangonzalez** [comment]
Do you have any advice to guard around that?

**Comment by desandro** [comment]
Sorry, no.

As I do not have access to your environment, I'm not exactly sure where the problem truly lies. It may be with staticClick being triggered automatically somewhere. I can only guess.

**Comment by briangonzalez** [comment]
Ok, thanks Dave. We'll dig around some more on our side and keep you posted with our findings. Appreciate the help thus far.
