### ISSUE TITLE
matches-selector.git#2.0.2 stops installing

### ISSUE THREAD

**Issue by Rohit-Parte** [desandro/matches-selector#8]
Hi @desandro ,
When we are installing bower.json file , suddenly stops installation at  
bower cached        https://github.com/desandro/matches-selector.git#2.0.2
bower validate      2.0.2 against https://github.com/desandro/matches-selector.git#^2.0.0
![screenshot from 2017-11-26 19-42-56](https://user-images.githubusercontent.com/33453608/33240804-2d65574a-d2e2-11e7-9296-e0da1f6c494b.png)

**Comment by desandro** [comment]
Have you updated Bower to use the latest registry? Should be 1.8.2

``` bash
bower -v
# 1.8.2
```

**Comment by fcosantos** [comment]
To see what is really happening you should do:
```bash
bower -V i
```
